Make add/move/replace media items calls in `MockPlayer` safer
MockPlayer naively calls `Util.moveItems` and `Util.removeRange` without properly checking or clamping the index bounds.

When out-of-bounds indices are fed to Util.moveItems or Util.removeRange, they trigger exceptions such as `IndexOutOfBoundsException` or `IllegalArgumentException`, causing the asynchronous `RemoteMediaSession` handler thread to unexpectedly crash.

Logs

```shell
> Task :test-session-current:connectedDebugAndroidTest
Logcat of last crash:
Process: androidx.media3.test.session:remote, PID: 15308
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:385)
	at java.util.ArrayList.remove(ArrayList.java:558)
	at androidx.media3.common.util.Util.moveItems(Util.java:3838)
	at androidx.media3.session.MockPlayer.moveMediaItems(MockPlayer.java:1109)
	at androidx.media3.common.ForwardingPlayer.moveMediaItems(ForwardingPlayer.java:182)
```
PiperOrigin-RevId: 915386474