Ensure consistent use of `PlaybackStateCompat`
This class was already using the media1 version of
`android.support.v4.media.session.PlaybackStateCompat` but a recent [1]
static import pulled in the `STATE_STOPPED` constant from the
`media3.legacy` version of the same class, leading to a lint error:

```
MediaSessionCompatProviderService.java:287: Error: Must be one of: PlaybackStateCompat.STATE_NONE, PlaybackStateCompat.STATE_STOPPED, PlaybackStateCompat.STATE_PAUSED, PlaybackStateCompat.STATE_PLAYING, PlaybackStateCompat.STATE_FAST_FORWARDING, PlaybackStateCompat.STATE_REWINDING, PlaybackStateCompat.STATE_BUFFERING, PlaybackStateCompat.STATE_ERROR, PlaybackStateCompat.STATE_CONNECTING, PlaybackStateCompat.STATE_SKIPPING_TO_PREVIOUS, PlaybackStateCompat.STATE_SKIPPING_TO_NEXT, PlaybackStateCompat.STATE_SKIPPING_TO_QUEUE_ITEM [WrongConstant]
                        STATE_STOPPED,
```

[1] https://github.com/androidx/media/commit/3959b183ff5b10073cd71ac207852d8ca4448cdd

PiperOrigin-RevId: 851305256
(cherry picked from commit c90f107b48dcc0fc3de60f34965266c092049662)